### ISSUE TITLE
Android this is not an activity

### ISSUE THREAD

**Issue by fbacker** [react-native-component/react-native-smart-splash-screen#1]
When running on android I get the issue when adding package to MainActivity.java

     new RCTSplashScreenPackage(this)

Will crash on error

    MainApplication.java:41: error: incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity
          new RCTSplashScreenPackage(this)

**Comment by fbacker** [comment]
React 0.31

**Comment by cyqresig** [comment]
Registering Module for Android is different when using React 0.30+, 

first step: remove ReactNativeHost final defination,  and add next codes in MainApplication.java

//private final ReactNativeHost reactNativeHost = new ReactNativeHost(this) {
private ReactNativeHost reactNativeHost = new ReactNativeHost(this) {
    ...
}

public void setReactNativeHost(ReactNativeHost reactNativeHost) {
    this.reactNativeHost = reactNativeHost;
  }

second step: add next codes in MainActivity.java

    /**
     * A subclass may override this method if it needs to use a custom {@link ReactRootView}.
     */
    @Override
    protected ReactRootView createRootView() {

        MainApplication mainApplication=(MainApplication)this.getApplication();
        mainApplication.setReactNativeHost( new ReactNativeHost(mainApplication) {
            @Override
            protected boolean getUseDeveloperSupport() {
                return BuildConfig.DEBUG;
            }

            @Override
            protected List<ReactPackage> getPackages() {
                return Arrays.<ReactPackage>asList(
                        new MainReactPackage(),
                        new RCTSplashScreenPackage(MainActivity.this)  //register Module
                );
            }

        });

        return super.createRootView();
    }

**Comment by avishayil** [comment]
Still didn't figure it out. Can you put a working example for this?
