### ISSUE TITLE
Merge with rn-splash-screen

### ISSUE THREAD

**Issue by mehcode** [react-native-component/react-native-smart-splash-screen#2]
Hey @cyqresig  I like the customization you've done with animation!  

What do you think about consolidating with https://github.com/mehcode/rn-splash-screen ?

It's better for the community as a whole if we have one active and maintained "splash screen" package.

**Comment by cyqresig** [comment]
Thank you for your invitation. 
*rn-splash-screen*  is a very good and useful module I've ever used, but I prefer to write my own module, considering the maintainment, updates. 
I also wish to write it  alone for upgrading my skills.  
Thank you again for your understanding。 :)
