### ISSUE TITLE
how to Installation (Android)?

### ISSUE THREAD

**Issue by conan52** [react-native-component/react-native-smart-splash-screen#3]
Hi,
I want to use react-native-smart-splash-screen for android but i can't install for RN 30.
can you show file MainApplication.java and MainApplication.java?
Or can you create a example?
Thank you very much.

**Comment by cyqresig** [comment]
You can see this 
https://github.com/react-native-component/react-native-smart-splash-screen/issues/1

**Comment by cyqresig** [comment]
Now the README is updated. You can find the usage for react-native 0.30+(android).
