### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by therovermind** [react-native-component/react-native-smart-splash-screen#36]
![screenshot_20170828-163646](https://user-images.githubusercontent.com/16400492/29771064-9ee4d5d6-8c0f-11e7-8e18-add0ad8b0d6c.png).....
i get this error.How to resolve??
using RN- 0.47

**Comment by WolfieZero** [comment]
I'm getting the same issue with RN 0.46.3.

**Comment by WolfieZero** [comment]
Ah, I fixed it. Was an issue my end. I duplicated the method `getPackages()` in MainApplication.java rather than adding `new RCTSplashScreenPackage()` to the list.

**Comment by therovermind** [comment]
hey @WolfieZero thankyou..i made a similar mistake
