### ISSUE TITLE
Android does not work, bad Read Me

### ISSUE THREAD

**Issue by parkerdan** [react-native-component/react-native-smart-splash-screen#9]
If you create a new project, then follow your Read Me for React-Native versions > .30, it will not build.

**Comment by cyqresig** [comment]
Dear parkerdan,
The readme contains The installation for Android which supports react-native versions > 30.
You may check it more carefully, and you can try the full demo(https://github.com/cyqresig/ReactNativeComponentDemos).

**Comment by parkerdan** [comment]
Yeah... I did...your instructions are still wrong.  I forked it, fixed it, and improved it...but thanks for getting the ball rolling on this much needed package.

**Comment by dmdub** [comment]
@parkerdan How did you get this to work? I am still failing

**Comment by parkerdan** [comment]
See my GitHub,

**Comment by dmdub** [comment]
Thanks @parkerdan
